services:
  snowflake:
    build:
      context: .
      dockerfile: ./services/snowflake/Dockerfile
    ports:
      - 8001:80

  shortener:
    depends_on:
      - snowflake
      - shortener-psql
    build:
      context: .
      dockerfile: ./services/shortener/Dockerfile
    ports:
      - 8000:80

  shortener-psql:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=pw
    ports:
      - 5432:5432
