services:
  snowflake:
    build:
      context: .
      dockerfile: ./services/snowflake/Dockerfile
    ports:
      - 8001:8001

  shortener:
    depends_on:
      - snowflake
    build:
      context: .
      dockerfile: ./services/shortener/Dockerfile
    ports:
      - 8000:8000
