services:
  snowflake:
    build:
      context: .
      dockerfile: ./service.snowflake/Dockerfile
    ports:
      - 8001:8080

  shortener:
    depends_on:
      - snowflake
      - mysql
    build:
      context: .
      dockerfile: ./service.shortener/Dockerfile
    environment:
      - DATABASE_URL=root:pw@/shorturl
    ports:
      - 8000:8080

  mysql:
    image: mysql
    volumes:
      # Read service schema and init database (if required)
      - ./service.shortener/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: shorturl
    ports:
      - 3306:3306
