// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: snowflake.proto

package snowflake

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Snowflake_GetSnowflake_FullMethodName = "/Snowflake/GetSnowflake"
)

// SnowflakeClient is the client API for Snowflake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnowflakeClient interface {
	GetSnowflake(ctx context.Context, in *GetSnowflakeRequest, opts ...grpc.CallOption) (*GetSnowflakeResponse, error)
}

type snowflakeClient struct {
	cc grpc.ClientConnInterface
}

func NewSnowflakeClient(cc grpc.ClientConnInterface) SnowflakeClient {
	return &snowflakeClient{cc}
}

func (c *snowflakeClient) GetSnowflake(ctx context.Context, in *GetSnowflakeRequest, opts ...grpc.CallOption) (*GetSnowflakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnowflakeResponse)
	err := c.cc.Invoke(ctx, Snowflake_GetSnowflake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnowflakeServer is the server API for Snowflake service.
// All implementations must embed UnimplementedSnowflakeServer
// for forward compatibility.
type SnowflakeServer interface {
	GetSnowflake(context.Context, *GetSnowflakeRequest) (*GetSnowflakeResponse, error)
	mustEmbedUnimplementedSnowflakeServer()
}

// UnimplementedSnowflakeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnowflakeServer struct{}

func (UnimplementedSnowflakeServer) GetSnowflake(context.Context, *GetSnowflakeRequest) (*GetSnowflakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnowflake not implemented")
}
func (UnimplementedSnowflakeServer) mustEmbedUnimplementedSnowflakeServer() {}
func (UnimplementedSnowflakeServer) testEmbeddedByValue()                   {}

// UnsafeSnowflakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnowflakeServer will
// result in compilation errors.
type UnsafeSnowflakeServer interface {
	mustEmbedUnimplementedSnowflakeServer()
}

func RegisterSnowflakeServer(s grpc.ServiceRegistrar, srv SnowflakeServer) {
	// If the following call pancis, it indicates UnimplementedSnowflakeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Snowflake_ServiceDesc, srv)
}

func _Snowflake_GetSnowflake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnowflakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServer).GetSnowflake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Snowflake_GetSnowflake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServer).GetSnowflake(ctx, req.(*GetSnowflakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Snowflake_ServiceDesc is the grpc.ServiceDesc for Snowflake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Snowflake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Snowflake",
	HandlerType: (*SnowflakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnowflake",
			Handler:    _Snowflake_GetSnowflake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snowflake.proto",
}
