package common

const encodeBase62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

// takes an int64 value and converts it to a base62 string.
// This is being used here to get a shorter, more user-friendly
// version of the snowflake id generated by the snowflake service
func Base62(id int64) string {
	if id < 62 {
		return string(encodeBase62[id])
	}

	b := make([]byte, 0, 12)
	for id >= 62 {
		b = append(b, encodeBase62[id%62])
		id /= 62
	}
	b = append(b, encodeBase62[id])

	for x, y := 0, len(b)-1; x < y; x, y = x+1, y-1 {
		b[x], b[y] = b[y], b[x]
	}

	return string(b)
}
