name: ☁️ Deploy
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ☁️ Deploy
        run: docker build .
