name: ☁️ Deploy
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ☁️ Deploy
        run: make docker-build
